### ISSUE TITLE
[Bug]: Logged out status after device restart

### ISSUE THREAD

**Issue by 888594** [siddharthsky/CustTermux-JioTVGo#42]
### Problem description

latest version shows logged out every time device restarts then if you manually rerun it changes to logged in.

### What steps will reproduce the bug?

restart the device

### System information

```shell
mibox 4k
android 9
```

**Comment by siddharthsky** [comment]
> ### Problem description
> latest version shows logged out every time device restarts then if you manually rerun it changes to logged in.
> 
> ### What steps will reproduce the bug?
> restart the device
> 
> ### What is the expected behavior?
> _No response_
> 
> ### System information
> ```shell
> mibox 4k
> android 9
> ```

This issue is fixed in jiotvgo v3.9.3+.
Fresh install latest release.

**Comment by siddharthsky** [comment]
> ### Problem description
> latest version shows logged out every time device restarts then if you manually rerun it changes to logged in.
> 
> ### What steps will reproduce the bug?
> restart the device
> 
> ### What is the expected behavior?
> _No response_
> 
> ### System information
> ```shell
> mibox 4k
> android 9
> ```

This issue is fixed in jiotvgo v3.9.3+.
Fresh install latest release.

**Comment by 888594** [comment]
> > ### Problem description
> > latest version shows logged out every time device restarts then if you manually rerun it changes to logged in.
> > 
> > ### What steps will reproduce the bug?
> > restart the device
> > 
> > ### What is the expected behavior?
> > _No response_
> > 
> > ### System information
> > ```shell
> > mibox 4k
> > android 9
> > ```
> 
> This issue is fixed in jiotvgo v3.9.3+.
> Fresh install latest release.

Issue still persist. Logged out status after restart have to rerun.

**Comment by siddharthsky** [comment]
> > > ### Problem description
> > > latest version shows logged out every time device restarts then if you manually rerun it changes to logged in.
> > > ### What steps will reproduce the bug?
> > > restart the device
> > > ### What is the expected behavior?
> > > _No response_
> > > ### System information
> > > ```shell
> > > mibox 4k
> > > android 9
> > > ```
> > 
> > 
> > This issue is fixed in jiotvgo v3.9.3+.
> > Fresh install latest release.
> 
> Issue still persist. Logged out status after restart have to rerun.

Turn off login checker.
